/**
 * Content Script — runs in the context of the Zoom recording page.
 *
 * Responsibilities:
 *  1. Find the actual CDN video/audio URL from the Zoom player
 *  2. Collect session cookies (document.cookie only gives non-HttpOnly ones,
 *     but those are usually enough for yt-dlp to authenticate)
 *  3. Respond to messages from popup.js
 *
 * Why this works:
 *  The user is already authenticated in their browser.
 *  The content script runs in their session context, so it can access
 *  cookies and CDN URLs that are invisible to an external downloader.
 */

// ── Message listener ──────────────────────────────────────────────────────────
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.action === 'getZoomData') {
    const videoUrl = findVideoUrl();
    const cookies  = buildNetscapeCookies();
    sendResponse({ videoUrl, cookies });
  }
  return true; // Keep channel open for async response
});

// ── Find video URL ────────────────────────────────────────────────────────────
function findVideoUrl() {
  // Priority 1: direct <video> src (most common in Zoom player)
  const video = document.querySelector('video');
  if (video?.src && video.src.startsWith('http')) {
    console.log('[ZoomTranscriber] Found <video> src:', video.src);
    return video.src;
  }

  // Priority 2: <source> inside <video>
  const videoSource = document.querySelector('video source[src]');
  if (videoSource?.src) return videoSource.src;

  // Priority 3: <audio>
  const audio = document.querySelector('audio[src]');
  if (audio?.src) return audio.src;

  // Priority 4: XHR/Fetch intercepted blob URLs won't work — fall back to page URL
  // The backend will use the page URL + cookies to let yt-dlp figure out the CDN URL
  console.warn('[ZoomTranscriber] No direct media src found — using page URL');
  return window.location.href;
}

// ── Build Netscape cookie string ──────────────────────────────────────────────
function buildNetscapeCookies() {
  // document.cookie gives key=value pairs for non-HttpOnly cookies.
  // HttpOnly cookies (set by Zoom's auth server) are not accessible here,
  // but yt-dlp can also use --cookies-from-browser if needed.
  // The accessible cookies are usually sufficient for CDN auth.
  const domain = window.location.hostname;
  const pairs  = document.cookie.split(';').map(c => c.trim()).filter(Boolean);

  if (!pairs.length) return null;

  const lines = ['# Netscape HTTP Cookie File', '# Generated by Zoom Transcriber Extension', ''];
  pairs.forEach(pair => {
    const [name, ...rest] = pair.split('=');
    const value = rest.join('=');
    // Format: domain  include_subdomains  path  secure  expiry  name  value
    lines.push(`${domain}\tTRUE\t/\tFALSE\t0\t${name.trim()}\t${value.trim()}`);
  });

  return lines.join('\n');
}

// ── Auto-detect when video loads ──────────────────────────────────────────────
const observer = new MutationObserver(() => {
  const hasMedia = document.querySelector('video') || document.querySelector('audio');
  if (hasMedia) {
    chrome.storage.local.set({ mediaDetected: true, pageUrl: window.location.href });
  }
});

observer.observe(document.documentElement, { childList: true, subtree: true });

// Initial check
if (document.querySelector('video') || document.querySelector('audio')) {
  chrome.storage.local.set({ mediaDetected: true, pageUrl: window.location.href });
}
